version: '3'

volumes:
  pg_data:
  media:
  static:

services:
  foodgram_db:
    container_name: foodgram_db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  foodgram_backend:
    container_name: foodgram_backend
    depends_on:
      - foodgram_db
    image: eobgolts/foodgram_backend
    env_file: .env
    volumes:
     - media:/foodgram_media
     - ../data:/data
  frontend:
    container_name: foodgram_frontend
    image: eobgolts/foodgram_frontend
    volumes:
      - static:/app/result_build/
  nginx:
    container_name: foodgram_gateway
    image: nginx:1.19.3
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - media:/media
    depends_on:
      - foodgram_backend
      - frontend
