# Generated by Django 5.0 on 2023-12-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Тип ингредиента', 'verbose_name_plural': 'Типы ингредиентов'},
        ),
        migrations.AlterModelOptions(
            name='ingredientmeasurementunit',
            options={'verbose_name': 'Единица измерения', 'verbose_name_plural': 'Единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='ingredientvalue',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Имя ингредиента'),
        ),
        migrations.AlterField(
            model_name='ingredientmeasurementunit',
            name='measurement_unit',
            field=models.CharField(max_length=16, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredientvalue',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
    ]
