# Generated by Django 4.2.7 on 2023-12-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_userfavorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFavorite',
        ),
    ]
